driver:
    controllerType: Xbox
    rumble: false
    joysticks:
        left:
            horizontal: strafe
            vertical: throttle
        right:
            horizontal: rotation
    buttonpad:
        b: brakeMode
        a: autoTargetAlign
        y: toggleIntakeOuttake
    axes:
        rightTrigger: slowMode
        leftTrigger: turboMode
    buttons:
        start: zeroPose
    dpad:
        up: snapFromDriver
        down: snapToDriver
        left: snapLeft
        right: snapRight
operator:
    controllerType: Xbox
    rumble: false
    buttons:
        leftBumper: updatePoseWithCamera
demoMode: false