driver:
    controllerType: Xbox
    rumble: false
    joysticks:
        left:
            horizontal: strafe
            vertical: throttle
        right:
            horizontal: rotation
    buttonpad:
        b: brakeMode
        x: ampPivot
        a: collectorOuttake
    axes:
        rightTrigger: turboMode
        leftTrigger: slowMode
    buttons:
        start: zeroPose
        back: hardZeroPose
        leftBumper: shoot
    dpad:
        up: snapFromDriver
        down: snapToDriver
        left: snapLeft
        right: snapRight
operator:
    controllerType: Xbox
    rumble: false
    buttons:
        leftBumper: updatePoseWithCamera
    buttonpad:
        y: stopShooter
demoMode: false