driver:
    controllerType: Xbox
    rumble: false
    joysticks:
        left:
            horizontal: strafe
            vertical: throttle
        right:
            horizontal: rotation
    buttonpad:
        b: brakeMode
        x: ampPivot
    axes:
        rightTrigger: slowMode
        leftTrigger: turboMode
    buttons:
        start: zeroPose
        rightBumper: shoot
    dpad:
        up: snapFromDriver
        down: snapToDriver
        left: snapLeft
        right: snapRight
operator:
    controllerType: Xbox
    rumble: false
    buttons:
        leftBumper: updatePoseWithCamera
    buttonpad:
        y: StopShooter
demoMode: false