driver:
    controllerType: Xbox
    rumble: false
    joysticks:
        left:
            horizontal: strafe
            vertical: throttle
        right:
            horizontal: rotation
    buttonpad:
        b: brakeMode
        a: autoTargetAlign
        y: toggleIntakeOuttake
    axes:
        rightTrigger: slowMode
    buttons:
        start: zeroPose
    dpad:
        up: forwardRotate
        down: backwardRotate
        left: leftRotate
        right: rightRotate
operator:
    controllerType: Xbox
    rumble: false
    buttons:
        leftBumper: updatePoseWithCamera
demoMode: false