driver:
    controllerType: Xbox
    rumble: false
    joysticks:
        left:
            horizontal: strafe
            vertical: throttle
        right:
            horizontal: rotation
    buttonpad:
        b: brakeMode
        x: ampPivot
        a: collectorOuttake
        y: shootPivot
    axes:
        rightTrigger: turboMode
        leftTrigger: slowMode
    buttons:
        start: zeroPose
        back: hardZeroPose
        leftBumper: shoot
        rightBumper: reSpool
    dpad:
        up: snapToPickup
        down: snapToScore
        left: snapToBottomSpeaker
        right: snapToTopSpeaker
operator:
    controllerType: Xbox
    rumble: true
    buttons:
        leftBumper: climbSlow
        rightBumper: climbFast
    buttonpad:
        a: climbPosition
        y: stopShooter
buttonboard:
    center: reSpool
    left: zeroClimber
demoMode: false