driver:
  controllerType: Xbox
  rumble: true
  joysticks:
    left:
      horizontal: strafe
      vertical: throttle
    right:
      horizontal: rotation
  buttonpad:
    b: brakeMode
  axes:
    rightTrigger: turboMode
    leftTrigger: slowMode
operator:
  controllerType: Xbox
  rumble: true
  buttonpad:
    a: collectorOuttake
    b: stopShooter #remapped from y
    x: ampPivot
    y: shootPivot
  buttons:
    start: zeroPose
    back: hardZeroPose
    leftBumper: shoot
    rightBumper: rotateToPoint
  dpad:
    up: snapToPickup
    down: snapToScore
    left: snapToBottomSpeaker
    right: snapToTopSpeaker
buttonboard:
  upLeft: climbSlow
  upRight: climbFast
  up: climbPosition
  center: ShuttleRev
  left: zeroClimber
  downLeft: toggleOverride
  down: manualFeedingTransfer
demoMode: false