#FALLBACK yaml. This is a copy of zen.config.yml
subsystems:
    drivetrain:
        implemented: true
        motors:
            FLDr:
                motorType: TalonFX
                motorName: FLDr
                id: 1
                invertMotor: true
            FRDr:
                motorType: TalonFX
                motorName: FRDr
                id: 2
                invertMotor: false
            RLDr:
                motorType: TalonFX
                motorName: BLDr
                id: 3
                invertMotor: true
            RRDr:
                motorType: TalonFX
                motorName: BRDr
                id: 4
                invertMotor: false
            FLAz:
                motorType: TalonFX
                motorName: FLAz
                id: 5
                invertMotor: false
            FRAz:
                motorType: TalonFX
                motorName: FRAz
                id: 6
                invertMotor: false
            RLAz:
                motorType: TalonFX
                motorName: BLAz
                id: 7
                invertMotor: false
            RRAz:
                motorType: TalonFX
                motorName: BRAz
                id: 8
                invertMotor: false
        canCoders:
            FLEnc: 20
            FREnc: 21
            RLEnc: 22
            RREnc: 23
        invertCanCoder:
            - FLEnc
        swerveModules:
            modules:
                frontLeft:
                    drive: FLDr
                    azimuth: FLAz
                    canCoder: FLEnc
                    constants:
                        encoderOffset: 0.646240  #remote, -0.155273 rotor
                        invertSensorPhase: 1
                frontRight:
                    drive: FRDr
                    azimuth: FRAz
                    canCoder: FREnc
                    constants:
                        encoderOffset: 0.775391 #remote, -0.091797 rotor
                        invertSensorPhase: 1
                backLeft:
                    drive: RLDr
                    azimuth: RLAz
                    canCoder: RLEnc
                    constants:
                        encoderOffset: 0.444824 #remote, 0.049316 rotor
                        invertSensorPhase: 1
                backRight:
                    drive: RRDr
                    azimuth: RRAz
                    canCoder: RREnc
                    constants:
                        encoderOffset: 0.511475  #remote, -0.309082 rotor
                        invertSensorPhase: 1
            drivePID:
                slot0:
                    kP: 0.008007
                    kI: 0.002001
                    kD: 0.000400
                    kF: 0.009989
            azimuthPID:
                slot0:
                    kP: 7.6
                    kI: 1.5
                    kD: 0.15
                    kF: 0
                    allowableError: 5
        constants:
            ## Positional Configurations ##
            openLoopRampRate: 0.1
            isSwerve: 1
            encPPR: 14641
            azimuthEncPPR: 4096 
            wheelDiameter: 4
            kTrackScrubFactor: 1.0
            ## Velocity Constraints ##
            maxRotVel: 18
            trackWidth: 22.75 # inches
            wheelbaseLength: 22.75 # inches
            maxVelOpenLoop: 3.75 # meters/s (3.6)
            maxVelPathFollowing: 3.1 # meters/s (3.6)
            maxAccel: 1.5 # meters/s^2 (2.54)
            isDemoMode: 0
            ## Auto Balance ##
            autoBalanceDivider: 50
            autoBalanceThreshold: 2.5 # degrees
    camera:
        implemented: false
        constants:
            useMultiTargetOdometry: 1
infrastructure:
    canBusName: highSpeed
    ## Power Distribution ##
    pdId: 25
    pdIsRev: true
    ## Pneumatics Control ##
    compressorEnabled: false
    pcmIsRev: false
    pcmId: -1
    ## Pigeon ##
    pigeonId: 32
    isPigeon2: true
inputHandler: competition
constants:
    zeroingButton: 9 # channel of DIO port
    enableMusic: 0
    ## Drivetrain ##
    minAllowablePoseError: 0.1
    maxAllowablePoseError: 5
    soundOnConfig: 0 #If this is false, It will still beep on robot bootup.
    ## Logging ##
    logRobot: 1 # 0 or 1
    logDrivetrain: 1 # 0 or 1
    configStatusFrames: 0 # 0 or 1
    ## General ##
    teleopFieldCentric: 1 # 0 or 1
    kLooperDt: .025 # seconds
    resetFactoryDefaults: 1 # whether motors get reset to factory default
