#TODO update when we get it
subsystems:
    drivetrain:
        implemented: true
        motors:
            FLDr:
                motorType: TalonFX
                motorName: FLDr
                id: 1
                invertMotor: true
            FRDr:
                motorType: TalonFX
                motorName: FRDr
                id: 2
                invertMotor: true
            RLDr:
                motorType: TalonFX
                motorName: BLDr
                id: 3
                invertMotor: false
            RRDr:
                motorType: TalonFX
                motorName: BRDr
                id: 4
                invertMotor: false
            FLAz:
                motorType: TalonFX
                motorName: FLAz
                id: 5
                invertMotor: false
            FRAz:
                motorType: TalonFX
                motorName: FRAz
                id: 6
                invertMotor: false
            RLAz:
                motorType: TalonFX
                motorName: BLAz
                id: 7
                invertMotor: false
            RRAz:
                motorType: TalonFX
                motorName: BRAz
                id: 8
                invertMotor: false
        canCoders:
            FLEnc: 20
            FREnc: 21
            RLEnc: 22
            RREnc: 23
        invertCanCoder:
            - FLEnc
        swerveModules:
            modules:
                frontLeft:
                    drive: FLDr
                    azimuth: FLAz
                    canCoder: FLEnc
                    invertX: false
                    invertY: false
                    constants:
                        encoderOffset: 0.35302734375
                        couplingRatio: 3.589
                        freeSpin12VRPS: 100
                        invertSensorPhase: 1
                frontRight:
                    drive: FRDr
                    azimuth: FRAz
                    canCoder: FREnc
                    invertX: false
                    invertY: true
                    constants:
                        encoderOffset: -0.27294921875  #remote, -0.091797 rotor
                        couplingRatio: 3.572
                        freeSpin12VRPS: 101
                        invertSensorPhase: 1
                backLeft:
                    drive: RLDr
                    azimuth: RLAz
                    canCoder: RLEnc
                    invertX: true
                    invertY: false
                    constants:
                        encoderOffset: -0.009033203125 #feedback
                        couplingRatio: 3.576
                        freeSpin12VRPS: 104
                        invertSensorPhase: 1
                backRight:
                    drive: RRDr
                    azimuth: RRAz
                    canCoder: RREnc
                    invertX: true
                    invertY: true
                    constants:
                        encoderOffset: -0.015  #remote, -0.309082 rotor
                        couplingRatio: 3.579
                        freeSpin12VRPS: 102
                        invertSensorPhase: 1
            drivePID:
                slot0:
                    kP: 0.0065
                    kI: 0
                    kD: 0.00005
                    kF: 0.00925
            azimuthPID:
                slot0:
                    kP: 7
                    kI: 0
                    kD: 0
                    kF: 0
                    allowableError: 5
        constants:
            ## Positional Configurations ##
            maxVelTicks100ms: 12275.7 # ticks per 100ms, not changing bcs used in ghostmotor
            openLoopRampRate: 0.1
            isSwerve: 1
            isCTRSwerve: 1
            encPPR: 14641 #TODO
            azimuthEncPPR: 4096 #TODO
            wheelDiameter: 4
            kTrackScrubFactor: 1.0
            ## Velocity Constraints ##
            maxRotVel: 2 #Pi radians/sec
            trackWidth: 22.75 # inches
            wheelbaseLength: 22.75 # inches
            maxVelOpenLoop: 2.5 # meters/s (3.6)
            maxVel12VMPS: 4.9
            maxVelPathFollowing: 3.1 # meters/s (3.6)
            maxAccel: 1.5 # meters/s^2 (2.54)
            isDemoMode: 0
            ## Swerve Characterization ##
            driveGearRatio: 6.75 # L2
            azimuthGearRatio: 12.8 # MK4
            ## Auto Balance ##
            autoBalanceDivider: 50
            autoBalanceThreshold: 2.5 # degrees
    camera:
        implemented: false
        constants:
            useMultiTargetOdometry: 1
    collector:
        implemented: true
        motors:
            intakeMotor:
                motorType: TalonFX
                motorName: intakeMotor
                id: 10
                invertMotor: false
        pidConfig:
            slot0:
                kP: 0.043
                Ki: 0
                kD: 0.00001
                kF: 0.0099
        constants:
            intakeSpeed:  -80
            outtakeSpeed: 20
infrastructure:
    canBusName: highSpeed
    ## Power Distribution ##
    pdId: 25
    pdIsRev: true
    ## Pneumatics Control ##
    compressorEnabled: false
    pcmIsRev: false
    pcmId: -1
    ## Pigeon ##
    pigeonId: 32
    isPigeon2: true
inputHandler: competition
constants:
    zeroingButton: 9 # channel of DIO port
    ## Drivetrain ##
    minAllowablePoseError: 0.1
    maxAllowablePoseError: 5
    soundOnConfig: 0 #If this is false, It will still beep on robot bootup.
    ## Logging ##
    logRobot: 1 # 0 or 1
    logDrivetrain: 1 # 0 or 1
    configStatusFrames: 0 # 0 or 1
    ## General ##
    teleopFieldCentric: 1 # 0 or 1
    kLooperDt: .025 # seconds
    isProLicensed: 0
    resetFactoryDefaults: 1 # whether motors get reset to factory default