subsystems:
    drivetrain:
        implemented: true
        motors:
            FLDr:
                motorType: TalonFX
                motorName: FLDr
                id: 1
                invertMotor: false
            FRDr:
                motorType: TalonFX
                motorName: FRDr
                id: 2
                invertMotor: true
            RLDr:
                motorType: TalonFX
                motorName: BLDr
                id: 3
                invertMotor: false
            RRDr:
                motorType: TalonFX
                motorName: BRDr
                id: 4
                invertMotor: true
            FLAz:
                motorType: TalonFX
                motorName: FLAz
                id: 5
                invertMotor: false
            FRAz:
                motorType: TalonFX
                motorName: FRAz
                id: 6
                invertMotor: false
            RLAz:
                motorType: TalonFX
                motorName: BLAz
                id: 7
                invertMotor: false
            RRAz:
                motorType: TalonFX
                motorName: BRAz
                id: 8
                invertMotor: false
        canCoders:
            FLEnc: 20
            FREnc: 21
            RLEnc: 22
            RREnc: 23
        swerveModules:
            modules:
                frontLeft:
                    drive: FLDr
                    azimuth: FLAz
                    canCoder: FLEnc
                    invertX: false
                    invertY: false
                    constants:
                        encoderOffset: 0.352783203125
                        couplingRatio: 3.589
                        freeSpin12VRPS: 100
                        invertSensorPhase: 1
                frontRight:
                    drive: FRDr
                    azimuth: FRAz
                    canCoder: FREnc
                    invertX: false
                    invertY: true
                    constants:
                        encoderOffset: -0.262939453125
                        couplingRatio: 3.572
                        freeSpin12VRPS: 101
                        invertSensorPhase: 1
                backLeft:
                    drive: RLDr
                    azimuth: RLAz
                    canCoder: RLEnc
                    invertX: true
                    invertY: false
                    constants:
                        encoderOffset: -0.44482421875
                        couplingRatio: 3.576
                        freeSpin12VRPS: 104
                        invertSensorPhase: 1
                backRight:
                    drive: RRDr
                    azimuth: RRAz
                    canCoder: RREnc
                    invertX: true
                    invertY: true
                    constants:
                        encoderOffset: -0.0087890625
                        couplingRatio: 3.579
                        freeSpin12VRPS: 102
                        invertSensorPhase: 1
            drivePID:
                slot0:
                    kP: 0.0065
                    kI: 0
                    kD: 0.00005
                    kF: 0.00925
            azimuthPID:
                slot0:
                    kP: 7
                    kI: 0
                    kD: 0
                    kF: 0
                    allowableError: 5
        constants:
            ## Positional Configurations ##
            openLoopRampRate: 0.1
            isSwerve: 1
            isCTRSwerve: 1
            wheelDiameter: 3.7 #inches
            kTrackScrubFactor: 1.0
            ## Velocity Constraints ##
            maxRotVel: 0.8 # Pi radians/sec
            trackWidth: 22.75 # inches
            wheelbaseLength: 22.75 # inches
            maxVelOpenLoop: 2.5 # meters/s
            maxVel12VMPS: 4.9
            maxVelPathFollowing: 3.1 # meters/s
            maxAccel: 1.5 # meters/s^2
            isDemoMode: 0
            ## Swerve Characterization ##
            driveGearRatio: 6.75 # L2
            azimuthGearRatio: 12.8 # MK4
            ## Control Configurations ##
            slowModeScalar: 0.5
            turboModeScalar: 2
            driveDeadband: 0.1
            rotationalDeadband: 0.1
            inputDeadband: 0.15 # Deadband of the normalized input
    camera:
        implemented: false
        constants:
            useMultiTargetOdometry: 0
    collector:
        implemented: true
        motors:
            intakeMotor:
                motorType: TalonFX
                motorName: intakeMotor
                id: 10
                invertMotor: true
        pidConfig:
            slot0:
                kP: 0.043
                Ki: 0
                kD: 0.00001
                kF: 0.0099
        constants:
            intakeSpeed:  -0.8
            outtakeSpeed: 0.4
    shooter:
        implemented: true
        motors:
            rollerMotor:
                motorType: TalonFX
                motorName: rollerMotor
                id: 11
                invertMotor: false
            feederMotor:
                motorType: SparkMax
                motorName: feederMotor
                id: 9
                invertMotor: true
            pivotMotor:
                motorType: TalonFX
                motorName: pivotMotor
                id: 12
                invertMotor: false
                currentLimit: 20
                motionMagic:
                    expoKV: 0.05
                    expoKA: 0.06
            pivotFollowMotor:
                motorType: TalonFX
                motorName: pivotFollowMotor
                id: 13
                invertMotor: false # ?
                currentLimit: 20
        pidConfig:
            slot0:
                kP: 0
                Ki: 0
                kD: 0
                kF: 0.001
            slot1:
                kP: 0.00025
                Ki: 0
                kD: 0
                kF: 0.0105
            slot2:
                kP: 0.6
                ki: 0
                kD: 0.03
                kF: 0
                gravityType: cosine
        constants:
            noteSensorChannel: 0
            rollerSpeakerShootSpeed: 72
            rollerAmpShootSpeed: 30
            feederSpeakerShootSpeed: 700
            feederAmpShootSpeed: 700
            feederIntakeSpeed: 500
            velocityErrorMargin: 0.1
            pivotAmpShootPosition: 33
            invertFollowerMotor: 1
infrastructure:
    canBusName: highSpeed
    ## Power Distribution ##
    pdId: 1
    pdIsRev: true
    ## Pneumatics Control ##
    compressorEnabled: false
    pcmIsRev: false
    pcmId: -1
    ## Pigeon ##
    pigeonId: 32
    isPigeon2: true
inputHandler: competition
constants:
    zeroingButton: 9 # channel of DIO port
    enableMusic: 0
    ## Drivetrain ##
    minAllowablePoseError: 0.025
    maxAllowablePoseError: 5
    soundOnConfig: 0 #If this is false, It will still beep on robot bootup.
    ## Logging ##
    logRobot: 1 # 0 or 1
    logDrivetrain: 1 # 0 or 1
    configStatusFrames: 0 # 0 or 1
    ## General ##
    teleopFieldCentric: 1 # 0 or 1
    kLooperDt: .025 # seconds
    isProLicensed: 0
    hasCanivore: 1 # 0 or 1
    resetFactoryDefaults: 1 # whether motors get reset to factory default