subsystems:
    drivetrain:
        implemented: true
        motors:
            FLDr:
                motorType: TalonFX
                motorName: FLDr
                id: 7
                invertMotor: false
            FRDr:
                motorType: TalonFX
                motorName: FRDr
                id: 2
                invertMotor: true
            RLDr:
                motorType: TalonFX
                motorName: BLDr
                id: 8
                invertMotor: true
            RRDr:
                motorType: TalonFX
                motorName: BRDr
                id: 1
                invertMotor: true
            FLAz:
                motorType: TalonFX
                motorName: FLAz
                id: 12
                invertMotor: false
            FRAz:
                motorType: TalonFX
                motorName: FRAz
                id: 3
                invertMotor: false
            RLAz:
                motorType: TalonFX
                motorName: BLAz
                id: 9
                invertMotor: false
            RRAz:
                motorType: TalonFX
                motorName: BRAz
                id: 0
                invertMotor: false
        canCoders:
            FLEnc: 16
            FREnc: 15
            RLEnc: 17
            RREnc: 14
        swerveModules:
            modules:
                frontLeft:
                    drive: FLDr
                    azimuth: FLAz
                    canCoder: FLEnc
                    xCoord: 7.125
                    yCoord: 11.375
                    constants:
                        encoderOffset: -0.34228515625
                        couplingRatio: 3.576
                        freeSpin12VRPS: 101
                        invertSensorPhase: 1
                frontRight:
                    drive: FRDr
                    azimuth: FRAz
                    canCoder: FREnc
                    xCoord: 7.125
                    yCoord: -11.375
                    constants:
                        encoderOffset: -0.014404296875
                        couplingRatio: 3.579
                        freeSpin12VRPS: 101
                        invertSensorPhase: 1
                backLeft:
                    drive: RLDr
                    azimuth: RLAz
                    canCoder: RLEnc
                    xCoord: -11.375
                    yCoord: 11.375
                    constants:
                        encoderOffset: 0.23779296875
                        couplingRatio: 3.572
                        freeSpin12VRPS: 101
                        invertSensorPhase: 1
                backRight:
                    drive: RRDr
                    azimuth: RRAz
                    canCoder: RREnc
                    xCoord: -11.375
                    yCoord: -11.375
                    constants:
                        encoderOffset: 0.3076171875
                        couplingRatio: 3.589
                        freeSpin12VRPS: 104
                        invertSensorPhase: 1
            drivePID:
                slot0:
                    kP: 0.0065
                    kI: 0
                    kD: 0.00005
                    kF: 0.00925
            azimuthPID:
                slot0:
                    kP: 75
                    kI: 0
                    kD: 0
                    kF: 0
                    allowableError: 5
        constants:
            ## Positional Configurations ##
            openLoopRampRate: 0.1
            isSwerve: 1
            isCTRSwerve: 1 #TODO IF ALL ELSE FAILS
            wheelDiameter: 3.81 #inches
            kTrackScrubFactor: 1.0
            ## Velocity Constraints ##
            maxRotVel: 0.8 # Pi radians/sec
            maxRotVelClosedLoop: 2 # Pi radians/sec
            trackWidth: 22.75 # inches
            wheelbaseLength: 22.75 # inches
            maxVelOpenLoop: 3 # meters/s
            maxVel12VMPS: 5.2
            maxVelPathFollowing: 3.1 # meters/s
            maxAccel: 1.5 # meters/s^2
            isDemoMode: 0
            ## Swerve Characterization ##
            driveGearRatio: 6.12 # L2
            azimuthGearRatio: 12.8 # MK4
            ## Control Configurations ##
            slowModeScalar: 0.4
            turboModeScalar: 1.73
            driveDeadband: 0.1
            rotationalDeadband: 0.1
            inputDeadband: 0.15 # Deadband of the normalized input
            snapDivisor: 30
    camera:
        implemented: false
        constants:
            useMultiTargetOdometry: 0
    collector:
        implemented: true
        motors:
            intakeMotor:
                motorType: TalonFX
                motorName: intakeMotor
                id: 6
                invertMotor: false
        pidConfig:
            slot0:
                kP: 0.043
                Ki: 0
                kD: 0.00001
                kF: 0.0099
        constants:
            intakeSpeed: -0.75
            outtakeSpeed: 0.3
    shooter:
        implemented: true
        motors:
            rollerMotor:
                motorType: TalonFX
                motorName: rollerMotor
                id: 13
                invertMotor: false
            pivotMotor:
                motorType: TalonFX
                motorName: pivotMotor
                id: 10
                invertMotor: false
                currentLimit: 20
                motionMagic:
                    expoKV: 0.035
                    expoKA: 0.065
            pivotFollowMotor:
                motorType: TalonFX
                motorName: pivotFollowMotor
                id: 4
                invertMotor: false # ?
                currentLimit: 20
            feederMotor:
                motorType: TalonFX
                motorName: feederMotor
                id: 11
                invertMotor: true
        pidConfig:
            slot0:
                kP: 0.03
                Ki: 0
                kD: 0
                kF: 0.0105
            slot1:
                kP: 0.00025
                Ki: 0
                kD: 0
                kF: 0.0105
            slot2:
                kP: 0.6
                ki: 0
                kD: 0.02
                kF: 0
                gravityType: cosine
        canCoders:
            Pivot: 25
        constants:
            noteSensorChannel: 0
            rollerSpeakerShootSpeed: 71
            rollerAmpShootSpeed: 30
            rollerEjectShootSpeed: 65
            feederSpeakerShootSpeed: 30
            feederAmpShootSpeed: 11
            feederEjectShootSpeed: 28
            feederIntakeSpeed: 10.5
            velocityErrorMargin: 0.05
            velocityErrorMarginAutoAim: 0.003
            autoAimDegreeTolerance: .1
            pivotNeutralPosition: 1.5
            pivotAmpShootPosition: 33
            pivotDistanceShootPosition: 8.675
            invertFollowerMotor: 1
            canCoderOffset: 0.306
    climber:
        implemented: false
        motors:
            climbMotor:
                motorType: TalonFX
                motorName: climbMotor
                id: -14
                invertMotor: true
                currentLimit: 30
                enableCurrentLimit: true
        pidConfig:
            slot0:
                kP: 0.02
        constants:
            slowClimbPower: 0.3
            fastClimbPower: 0.8
            reSpoolPower: -0.5
            climbPosition: 194
            climbThreshold: 187
infrastructure:
    canBusName: highSpeed
    ## Power Distribution ##
    pdId: 1
    pdIsRev: true
    ## Pneumatics Control ##
    compressorEnabled: false
    pcmIsRev: false
    pcmId: -1
    ## Pigeon ##
    pigeonId: 5
    isPigeon2: true
inputHandler: drivercentric # the default input handler
constants:
    zeroingButton: 9 # channel of DIO port
    enableMusic: 0
    ## Drivetrain ##
    minAllowablePoseError: 0.025
    maxAllowablePoseError: 5
    soundOnConfig: 0 #If this is false, It will still beep on robot bootup.
    rotationToleranceClosedLoop: 0.5
    ## Logging ##
    logRobot: 1 # 0 or 1
    logDrivetrain: 1 # 0 or 1
    configStatusFrames: 0 # 0 or 1
    ## General ##
    usingVision: 0
    teleopFieldCentric: 1 # 0 or 1
    kLooperDt: .025 # seconds
    isProLicensed: 0
    hasCanivore: 1 # 0 or 1
    resetFactoryDefaults: 1 # whether motors get reset to factory default